### ISSUE TITLE
Exception with Timbre v6.3.1

### ISSUE THREAD

**Issue by dharrigan** [fzakaria/slf4j-timbre#74]
Hi,

`Clojure CLI version 1.11.1.1435`

```
openjdk 21.0.1 2023-10-17 LTS
OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (build 21.0.1+12-LTS, mixed mode, sharing)
```

```
com.fzakaria/slf4j-timbre {:mvn/version "0.4.1"}
com.taoensso/timbre {:mvn/version "6.3.1"}
```

When starting an application using these dependencies, the following is thrown:

```
2024-01-08T13:29:01 Exception in thread "main" java.lang.NoSuchFieldError: Class taoensso.timbre__init does not have member field 'clojure.lang.ILookupThunk __thunk__0__'
2024-01-08T13:29:01 	at taoensso.timbre__init.load(Unknown Source)
2024-01-08T13:29:01 	at taoensso.timbre__init.<clinit>(Unknown Source)
2024-01-08T13:29:01 	at java.base/java.lang.Class.forName0(Native Method)
2024-01-08T13:29:01 	at java.base/java.lang.Class.forName(Unknown Source)
2024-01-08T13:29:01 	at java.base/java.lang.Class.forName(Unknown Source)
2024-01-08T13:29:01 	at clojure.lang.RT.classForName(RT.java:2209)
2024-01-08T13:29:01 	at clojure.lang.RT.classForName(RT.java:2218)
2024-01-08T13:29:01 	at clojure.lang.RT.loadClassForName(RT.java:2237)
2024-01-08T13:29:01 	at clojure.lang.RT.load(RT.java:449)
2024-01-08T13:29:01 	at clojure.lang.RT.load(RT.java:424)
2024-01-08T13:29:01 	at clojure.core$load$fn__6908.invoke(core.clj:6161)
2024-01-08T13:29:01 	at clojure.core$load.invokeStatic(core.clj:6160)
2024-01-08T13:29:01 	at clojure.core$load.doInvoke(core.clj:6144)
2024-01-08T13:29:01 	at clojure.lang.RestFn.invoke(RestFn.java:408)
2024-01-08T13:29:01 	at clojure.core$load_one.invokeStatic(core.clj:5933)
2024-01-08T13:29:01 	at clojure.core$load_one.invoke(core.clj:5928)
2024-01-08T13:29:01 	at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
2024-01-08T13:29:01 	at clojure.core$load_lib.invokeStatic(core.clj:5974)
2024-01-08T13:29:01 	at clojure.core$load_lib.doInvoke(core.clj:5953)
2024-01-08T13:29:01 	at clojure.lang.RestFn.applyTo(RestFn.java:142)
2024-01-08T13:29:01 	at clojure.core$apply.invokeStatic(core.clj:669)
2024-01-08T13:29:01 	at clojure.core$load_libs.invokeStatic(core.clj:6016)
2024-01-08T13:29:01 	at clojure.core$load_libs.doInvoke(core.clj:6000)
2024-01-08T13:29:01 	at clojure.lang.RestFn.applyTo(RestFn.java:137)
2024-01-08T13:29:01 	at clojure.core$apply.invokeStatic(core.clj:669)
2024-01-08T13:29:01 	at clojure.core$require.invokeStatic(core.clj:6038)
2024-01-08T13:29:01 	at clojure.core$require.doInvoke(core.clj:6038)
2024-01-08T13:29:01 	at clojure.lang.RestFn.invoke(RestFn.java:421)
2024-01-08T13:29:01 	at slf4j_timbre.adapter$loading__6789__auto____171.invoke(adapter.clj:1)
2024-01-08T13:29:01 	at slf4j_timbre.adapter__init.load(Unknown Source)
2024-01-08T13:29:01 	at slf4j_timbre.adapter__init.<clinit>(Unknown Source)
2024-01-08T13:29:01 	at java.base/java.lang.Class.forName0(Native Method)
...
...
...
```

Reverting to `com.taoensso/timbre {:mvn/version "6.2.2"}` does not produce an error.

Do let me know if you require any further information.

Thank you.

-=david=-

**Comment by mike706574** [comment]
We're running into this as well when we try to upgrade Timbre.

**Comment by ptaoussanis** [comment]
@dharrigan @mike706574 Hi David, Mike - in case this is still relevant for you, you might want to try [Timbre v6.6.0-RC1](https://github.com/taoensso/timbre/releases/tag/v6.6.0-RC1) which now includes [built-in SLF4J(v2) support](https://github.com/taoensso/timbre/wiki/4-Interop#java-logging) that'll always be automatically kept in-sync with the latest Timbre release.

**Comment by dharrigan** [comment]
Thank you, will do!
